import { MigrationInterface, QueryRunner } from "typeorm";

export class InitMigration1765403466165 implements MigrationInterface {
    name = 'InitMigration1765403466165'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_membership" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "rol" varchar CHECK( "rol" IN ('PROPIETARIO','MIEMBRO') ) NOT NULL DEFAULT ('MIEMBRO'), "fechaIngreso" datetime NOT NULL DEFAULT (datetime('now')), "userId" integer NOT NULL, "teamId" integer NOT NULL, CONSTRAINT "UQ_8cbaee95bef7db57d99430b302b" UNIQUE ("userId", "teamId"), CONSTRAINT "FK_f587b1be7b7595b5af79a2fd008" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_eef2d9d9c70cd13bed868afedf4" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_membership"("id", "rol", "fechaIngreso", "userId", "teamId") SELECT "id", "rol", "fechaIngreso", "userId", "teamId" FROM "membership"`);
        await queryRunner.query(`DROP TABLE "membership"`);
        await queryRunner.query(`ALTER TABLE "temporary_membership" RENAME TO "membership"`);
        await queryRunner.query(`CREATE TABLE "task_template" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "description" text, "priority" varchar CHECK( "priority" IN ('HIGH','MEDIUM','LOW') ) NOT NULL DEFAULT ('MEDIUM'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "teamId" integer, "creatorId" integer NOT NULL, CONSTRAINT "UQ_66c6d9582702c3c8294d26ce419" UNIQUE ("name", "creatorId"))`);
        await queryRunner.query(`CREATE TABLE "template_etiquetas" ("template_id" integer NOT NULL, "etiqueta_id" integer NOT NULL, PRIMARY KEY ("template_id", "etiqueta_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_615a13c38943ab11c5983c7890" ON "template_etiquetas" ("template_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5e630addb95f5c5f6aa0fabeba" ON "template_etiquetas" ("etiqueta_id") `);
        await queryRunner.query(`CREATE TABLE "temporary_task" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar NOT NULL, "description" varchar NOT NULL, "userId" integer, "teamId" integer, "priority" text NOT NULL DEFAULT ('media'), "estado" varchar CHECK( "estado" IN ('PENDIENTE','EN_CURSO','FINALIZADA','CANCELADA') ) NOT NULL DEFAULT ('PENDIENTE'), "dueDate" datetime, "fechaCreacion" datetime NOT NULL DEFAULT (datetime('now')), "historialEstadosId" integer, "originTemplateId" integer, CONSTRAINT "FK_81dff849ce37d44c8821afdb197" FOREIGN KEY ("historialEstadosId") REFERENCES "historial_estado" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_f316d3fe53497d4d8a2957db8b9" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_de59b0c5e20f83310101e5ca835" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_task"("id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId") SELECT "id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId" FROM "task"`);
        await queryRunner.query(`DROP TABLE "task"`);
        await queryRunner.query(`ALTER TABLE "temporary_task" RENAME TO "task"`);
        await queryRunner.query(`CREATE TABLE "temporary_membership" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "rol" varchar CHECK( "rol" IN ('PROPIETARIO','MIEMBRO') ) NOT NULL DEFAULT ('MIEMBRO'), "fechaIngreso" datetime NOT NULL DEFAULT (datetime('now')), "userId" integer NOT NULL, "teamId" integer NOT NULL, CONSTRAINT "UQ_8cbaee95bef7db57d99430b302b" UNIQUE ("userId", "teamId"), CONSTRAINT "FK_f587b1be7b7595b5af79a2fd008" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_eef2d9d9c70cd13bed868afedf4" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_membership"("id", "rol", "fechaIngreso", "userId", "teamId") SELECT "id", "rol", "fechaIngreso", "userId", "teamId" FROM "membership"`);
        await queryRunner.query(`DROP TABLE "membership"`);
        await queryRunner.query(`ALTER TABLE "temporary_membership" RENAME TO "membership"`);
        await queryRunner.query(`CREATE TABLE "temporary_task" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar NOT NULL, "description" varchar NOT NULL, "userId" integer, "teamId" integer, "priority" text NOT NULL DEFAULT ('media'), "estado" varchar CHECK( "estado" IN ('PENDIENTE','EN_CURSO','FINALIZADA','CANCELADA') ) NOT NULL DEFAULT ('PENDIENTE'), "dueDate" datetime, "fechaCreacion" datetime NOT NULL DEFAULT (datetime('now')), "historialEstadosId" integer, "originTemplateId" integer, CONSTRAINT "FK_81dff849ce37d44c8821afdb197" FOREIGN KEY ("historialEstadosId") REFERENCES "historial_estado" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_f316d3fe53497d4d8a2957db8b9" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_de59b0c5e20f83310101e5ca835" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_task"("id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId", "originTemplateId") SELECT "id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId", "originTemplateId" FROM "task"`);
        await queryRunner.query(`DROP TABLE "task"`);
        await queryRunner.query(`ALTER TABLE "temporary_task" RENAME TO "task"`);
        await queryRunner.query(`CREATE TABLE "temporary_task_template" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "description" text, "priority" varchar CHECK( "priority" IN ('HIGH','MEDIUM','LOW') ) NOT NULL DEFAULT ('MEDIUM'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "teamId" integer, "creatorId" integer NOT NULL, CONSTRAINT "UQ_66c6d9582702c3c8294d26ce419" UNIQUE ("name", "creatorId"), CONSTRAINT "FK_41773244ecf2bcb7f64d97db8c6" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_df3b5923b5d8c6289bce8c3aa04" FOREIGN KEY ("creatorId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_task_template"("id", "name", "description", "priority", "createdAt", "updatedAt", "teamId", "creatorId") SELECT "id", "name", "description", "priority", "createdAt", "updatedAt", "teamId", "creatorId" FROM "task_template"`);
        await queryRunner.query(`DROP TABLE "task_template"`);
        await queryRunner.query(`ALTER TABLE "temporary_task_template" RENAME TO "task_template"`);
        await queryRunner.query(`CREATE TABLE "temporary_task" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar NOT NULL, "description" varchar NOT NULL, "userId" integer, "teamId" integer, "priority" text NOT NULL DEFAULT ('media'), "estado" varchar CHECK( "estado" IN ('PENDIENTE','EN_CURSO','FINALIZADA','CANCELADA') ) NOT NULL DEFAULT ('PENDIENTE'), "dueDate" datetime, "fechaCreacion" datetime NOT NULL DEFAULT (datetime('now')), "historialEstadosId" integer, "originTemplateId" integer, CONSTRAINT "FK_81dff849ce37d44c8821afdb197" FOREIGN KEY ("historialEstadosId") REFERENCES "historial_estado" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_f316d3fe53497d4d8a2957db8b9" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_de59b0c5e20f83310101e5ca835" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_9b90b475c5fe8a21df947befddf" FOREIGN KEY ("originTemplateId") REFERENCES "task_template" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_task"("id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId", "originTemplateId") SELECT "id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId", "originTemplateId" FROM "task"`);
        await queryRunner.query(`DROP TABLE "task"`);
        await queryRunner.query(`ALTER TABLE "temporary_task" RENAME TO "task"`);
        await queryRunner.query(`DROP INDEX "IDX_615a13c38943ab11c5983c7890"`);
        await queryRunner.query(`DROP INDEX "IDX_5e630addb95f5c5f6aa0fabeba"`);
        await queryRunner.query(`CREATE TABLE "temporary_template_etiquetas" ("template_id" integer NOT NULL, "etiqueta_id" integer NOT NULL, CONSTRAINT "FK_615a13c38943ab11c5983c78906" FOREIGN KEY ("template_id") REFERENCES "task_template" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_5e630addb95f5c5f6aa0fabeba6" FOREIGN KEY ("etiqueta_id") REFERENCES "etiqueta" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("template_id", "etiqueta_id"))`);
        await queryRunner.query(`INSERT INTO "temporary_template_etiquetas"("template_id", "etiqueta_id") SELECT "template_id", "etiqueta_id" FROM "template_etiquetas"`);
        await queryRunner.query(`DROP TABLE "template_etiquetas"`);
        await queryRunner.query(`ALTER TABLE "temporary_template_etiquetas" RENAME TO "template_etiquetas"`);
        await queryRunner.query(`CREATE INDEX "IDX_615a13c38943ab11c5983c7890" ON "template_etiquetas" ("template_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5e630addb95f5c5f6aa0fabeba" ON "template_etiquetas" ("etiqueta_id") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_5e630addb95f5c5f6aa0fabeba"`);
        await queryRunner.query(`DROP INDEX "IDX_615a13c38943ab11c5983c7890"`);
        await queryRunner.query(`ALTER TABLE "template_etiquetas" RENAME TO "temporary_template_etiquetas"`);
        await queryRunner.query(`CREATE TABLE "template_etiquetas" ("template_id" integer NOT NULL, "etiqueta_id" integer NOT NULL, PRIMARY KEY ("template_id", "etiqueta_id"))`);
        await queryRunner.query(`INSERT INTO "template_etiquetas"("template_id", "etiqueta_id") SELECT "template_id", "etiqueta_id" FROM "temporary_template_etiquetas"`);
        await queryRunner.query(`DROP TABLE "temporary_template_etiquetas"`);
        await queryRunner.query(`CREATE INDEX "IDX_5e630addb95f5c5f6aa0fabeba" ON "template_etiquetas" ("etiqueta_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_615a13c38943ab11c5983c7890" ON "template_etiquetas" ("template_id") `);
        await queryRunner.query(`ALTER TABLE "task" RENAME TO "temporary_task"`);
        await queryRunner.query(`CREATE TABLE "task" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar NOT NULL, "description" varchar NOT NULL, "userId" integer, "teamId" integer, "priority" text NOT NULL DEFAULT ('media'), "estado" varchar CHECK( "estado" IN ('PENDIENTE','EN_CURSO','FINALIZADA','CANCELADA') ) NOT NULL DEFAULT ('PENDIENTE'), "dueDate" datetime, "fechaCreacion" datetime NOT NULL DEFAULT (datetime('now')), "historialEstadosId" integer, "originTemplateId" integer, CONSTRAINT "FK_81dff849ce37d44c8821afdb197" FOREIGN KEY ("historialEstadosId") REFERENCES "historial_estado" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_f316d3fe53497d4d8a2957db8b9" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_de59b0c5e20f83310101e5ca835" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "task"("id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId", "originTemplateId") SELECT "id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId", "originTemplateId" FROM "temporary_task"`);
        await queryRunner.query(`DROP TABLE "temporary_task"`);
        await queryRunner.query(`ALTER TABLE "task_template" RENAME TO "temporary_task_template"`);
        await queryRunner.query(`CREATE TABLE "task_template" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "description" text, "priority" varchar CHECK( "priority" IN ('HIGH','MEDIUM','LOW') ) NOT NULL DEFAULT ('MEDIUM'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "teamId" integer, "creatorId" integer NOT NULL, CONSTRAINT "UQ_66c6d9582702c3c8294d26ce419" UNIQUE ("name", "creatorId"))`);
        await queryRunner.query(`INSERT INTO "task_template"("id", "name", "description", "priority", "createdAt", "updatedAt", "teamId", "creatorId") SELECT "id", "name", "description", "priority", "createdAt", "updatedAt", "teamId", "creatorId" FROM "temporary_task_template"`);
        await queryRunner.query(`DROP TABLE "temporary_task_template"`);
        await queryRunner.query(`ALTER TABLE "task" RENAME TO "temporary_task"`);
        await queryRunner.query(`CREATE TABLE "task" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar NOT NULL, "description" varchar NOT NULL, "userId" integer, "teamId" integer, "priority" text NOT NULL DEFAULT ('media'), "estado" varchar CHECK( "estado" IN ('PENDIENTE','EN_CURSO','FINALIZADA','CANCELADA') ) NOT NULL DEFAULT ('PENDIENTE'), "dueDate" datetime, "fechaCreacion" datetime NOT NULL DEFAULT (datetime('now')), "historialEstadosId" integer, "originTemplateId" integer, CONSTRAINT "FK_81dff849ce37d44c8821afdb197" FOREIGN KEY ("historialEstadosId") REFERENCES "historial_estado" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_f316d3fe53497d4d8a2957db8b9" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_de59b0c5e20f83310101e5ca835" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "task"("id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId", "originTemplateId") SELECT "id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId", "originTemplateId" FROM "temporary_task"`);
        await queryRunner.query(`DROP TABLE "temporary_task"`);
        await queryRunner.query(`ALTER TABLE "membership" RENAME TO "temporary_membership"`);
        await queryRunner.query(`CREATE TABLE "membership" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "rol" varchar CHECK( "rol" IN ('PROPIETARIO','MIEMBRO') ) NOT NULL DEFAULT ('MIEMBRO'), "fechaIngreso" datetime NOT NULL DEFAULT (datetime('now')), "userId" integer NOT NULL, "teamId" integer NOT NULL, CONSTRAINT "UQ_8cbaee95bef7db57d99430b302b" UNIQUE ("userId", "teamId"), CONSTRAINT "FK_f587b1be7b7595b5af79a2fd008" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_eef2d9d9c70cd13bed868afedf4" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "membership"("id", "rol", "fechaIngreso", "userId", "teamId") SELECT "id", "rol", "fechaIngreso", "userId", "teamId" FROM "temporary_membership"`);
        await queryRunner.query(`DROP TABLE "temporary_membership"`);
        await queryRunner.query(`ALTER TABLE "task" RENAME TO "temporary_task"`);
        await queryRunner.query(`CREATE TABLE "task" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar NOT NULL, "description" varchar NOT NULL, "userId" integer, "teamId" integer, "priority" text NOT NULL DEFAULT ('media'), "estado" varchar CHECK( "estado" IN ('PENDIENTE','EN_CURSO','FINALIZADA','CANCELADA') ) NOT NULL DEFAULT ('PENDIENTE'), "dueDate" datetime, "fechaCreacion" datetime NOT NULL DEFAULT (datetime('now')), "historialEstadosId" integer, CONSTRAINT "FK_81dff849ce37d44c8821afdb197" FOREIGN KEY ("historialEstadosId") REFERENCES "historial_estado" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_f316d3fe53497d4d8a2957db8b9" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_de59b0c5e20f83310101e5ca835" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "task"("id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId") SELECT "id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId" FROM "temporary_task"`);
        await queryRunner.query(`DROP TABLE "temporary_task"`);
        await queryRunner.query(`DROP INDEX "IDX_5e630addb95f5c5f6aa0fabeba"`);
        await queryRunner.query(`DROP INDEX "IDX_615a13c38943ab11c5983c7890"`);
        await queryRunner.query(`DROP TABLE "template_etiquetas"`);
        await queryRunner.query(`DROP TABLE "task_template"`);
        await queryRunner.query(`ALTER TABLE "membership" RENAME TO "temporary_membership"`);
        await queryRunner.query(`CREATE TABLE "membership" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "rol" varchar CHECK( "rol" IN ('PROPIETARIO','MIEMBRO') ) NOT NULL DEFAULT ('MIEMBRO'), "fechaIngreso" datetime NOT NULL DEFAULT (datetime('now')), "userId" integer NOT NULL, "teamId" integer NOT NULL, CONSTRAINT "UQ_8cbaee95bef7db57d99430b302b" UNIQUE ("userId", "teamId"), CONSTRAINT "FK_f587b1be7b7595b5af79a2fd008" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_eef2d9d9c70cd13bed868afedf4" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "membership"("id", "rol", "fechaIngreso", "userId", "teamId") SELECT "id", "rol", "fechaIngreso", "userId", "teamId" FROM "temporary_membership"`);
        await queryRunner.query(`DROP TABLE "temporary_membership"`);
    }

}
